// spotless:off
package frc.robot.auto;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import java.util.Map;
import java.util.OptionalInt;

import choreo.auto.AutoRoutine;
import choreo.auto.AutoTrajectory;
// If the 2 imports above cause errors because you're not using ChoreoLib,
// turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.

/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories,
 * and removes the need for JSON parsing to load a trajectory's essential data.
 * DO NOT MODIFY THIS FILE YOURSELF! It is automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    OptionalInt segment,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue
) {
    public static final ChoreoTraj CalibrateMOI = new ChoreoTraj(
        "CalibrateMOI",
        OptionalInt.empty(),
        13.17337,
        new Pose2d(1.8288, 1.8288, Rotation2d.fromRadians(0)),
        new Pose2d(1.8288, 1.8288, Rotation2d.fromRadians(0))
    );
    public static final ChoreoTraj ShootDepot = new ChoreoTraj(
        "ShootDepot",
        OptionalInt.empty(),
        11.08099,
        new Pose2d(3.54902, 4.00775, Rotation2d.fromRadians(3.14159)),
        new Pose2d(1.00236, 4.50159, Rotation2d.fromRadians(1.5708))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj ShootDepot$0 = new ChoreoTraj(
        "ShootDepot",
        OptionalInt.of(0),
        4.18974,
        new Pose2d(3.54902, 4.00775, Rotation2d.fromRadians(3.14159)),
        new Pose2d(0.81357, 5.98337, Rotation2d.fromRadians(3.14159))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj ShootDepot$1 = new ChoreoTraj(
        "ShootDepot",
        OptionalInt.of(1),
        5.205660000000001,
        new Pose2d(0.81357, 5.98337, Rotation2d.fromRadians(3.14159)),
        new Pose2d(0.98966, 5.00743, Rotation2d.fromRadians(1.5708))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj ShootDepot$2 = new ChoreoTraj(
        "ShootDepot",
        OptionalInt.of(2),
        1.6855899999999995,
        new Pose2d(0.98966, 5.00743, Rotation2d.fromRadians(1.5708)),
        new Pose2d(1.00236, 4.50159, Rotation2d.fromRadians(1.5708))
    );
    public static final ChoreoTraj Trench1xDepot = new ChoreoTraj(
        "Trench1xDepot",
        OptionalInt.empty(),
        8.0131,
        new Pose2d(4.25199, 7.44921, Rotation2d.fromRadians(0)),
        new Pose2d(2.62876, 6.29791, Rotation2d.fromRadians(2.2939))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj Trench1xDepot$0 = new ChoreoTraj(
        "Trench1xDepot",
        OptionalInt.of(0),
        6.37261,
        new Pose2d(4.25199, 7.44921, Rotation2d.fromRadians(0)),
        new Pose2d(6.04103, 7.46993, Rotation2d.fromRadians(0))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj Trench1xDepot$1 = new ChoreoTraj(
        "Trench1xDepot",
        OptionalInt.of(1),
        1.6404899999999998,
        new Pose2d(6.04103, 7.46993, Rotation2d.fromRadians(0)),
        new Pose2d(2.62876, 6.29791, Rotation2d.fromRadians(2.2939))
    );
    public static final ChoreoTraj Trench1xDepotClimb = new ChoreoTraj(
        "Trench1xDepotClimb",
        OptionalInt.empty(),
        17.50836,
        new Pose2d(4.25199, 7.44921, Rotation2d.fromRadians(0)),
        new Pose2d(1.00236, 4.50159, Rotation2d.fromRadians(1.5708))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj Trench1xDepotClimb$0 = new ChoreoTraj(
        "Trench1xDepotClimb",
        OptionalInt.of(0),
        6.31091,
        new Pose2d(4.25199, 7.44921, Rotation2d.fromRadians(0)),
        new Pose2d(6.04103, 7.46993, Rotation2d.fromRadians(0))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj Trench1xDepotClimb$1 = new ChoreoTraj(
        "Trench1xDepotClimb",
        OptionalInt.of(1),
        1.3401800000000001,
        new Pose2d(6.04103, 7.46993, Rotation2d.fromRadians(0)),
        new Pose2d(2.22425, 7.13992, Rotation2d.fromRadians(1.54298))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj Trench1xDepotClimb$2 = new ChoreoTraj(
        "Trench1xDepotClimb",
        OptionalInt.of(2),
        5.62097,
        new Pose2d(2.22425, 7.13992, Rotation2d.fromRadians(1.54298)),
        new Pose2d(1.43891, 5.6179, Rotation2d.fromRadians(1.54298))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj Trench1xDepotClimb$3 = new ChoreoTraj(
        "Trench1xDepotClimb",
        OptionalInt.of(3),
        4.2363,
        new Pose2d(1.43891, 5.6179, Rotation2d.fromRadians(1.54298)),
        new Pose2d(1.00236, 4.50159, Rotation2d.fromRadians(1.5708))
    );
    public static final ChoreoTraj Trench2xOutpost = new ChoreoTraj(
        "Trench2xOutpost",
        OptionalInt.empty(),
        13.45788,
        new Pose2d(4.25199, 0.62799, Rotation2d.fromRadians(0)),
        new Pose2d(3.34792, 0.52639, Rotation2d.fromRadians(0))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj Trench2xOutpost$0 = new ChoreoTraj(
        "Trench2xOutpost",
        OptionalInt.of(0),
        6.46571,
        new Pose2d(4.25199, 0.62799, Rotation2d.fromRadians(0)),
        new Pose2d(6.59219, 0.78039, Rotation2d.fromRadians(0))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj Trench2xOutpost$1 = new ChoreoTraj(
        "Trench2xOutpost",
        OptionalInt.of(1),
        1.51194,
        new Pose2d(6.59219, 0.78039, Rotation2d.fromRadians(0)),
        new Pose2d(3.3439, 0.52639, Rotation2d.fromRadians(0))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj Trench2xOutpost$2 = new ChoreoTraj(
        "Trench2xOutpost",
        OptionalInt.of(2),
        1.3221200000000009,
        new Pose2d(3.3439, 0.52639, Rotation2d.fromRadians(0)),
        new Pose2d(6.13499, 0.67879, Rotation2d.fromRadians(0))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj Trench2xOutpost$3 = new ChoreoTraj(
        "Trench2xOutpost",
        OptionalInt.of(3),
        2.9230199999999993,
        new Pose2d(6.13499, 0.67879, Rotation2d.fromRadians(0)),
        new Pose2d(5.97501, 0.57719, Rotation2d.fromRadians(0))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj Trench2xOutpost$4 = new ChoreoTraj(
        "Trench2xOutpost",
        OptionalInt.of(4),
        1.2350899999999996,
        new Pose2d(5.97501, 0.57719, Rotation2d.fromRadians(0)),
        new Pose2d(3.34792, 0.52639, Rotation2d.fromRadians(0))
    );

    /**
     * A map between trajectory names and their corresponding data.
     * This allows for trajectory data to be looked up with strings during runtime.
     */
    public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES = Map.ofEntries(
        Map.entry("CalibrateMOI", CalibrateMOI),
        Map.entry("ShootDepot", ShootDepot),
        Map.entry("ShootDepot$0", ShootDepot$0),
        Map.entry("ShootDepot$1", ShootDepot$1),
        Map.entry("ShootDepot$2", ShootDepot$2),
        Map.entry("Trench1xDepot", Trench1xDepot),
        Map.entry("Trench1xDepot$0", Trench1xDepot$0),
        Map.entry("Trench1xDepot$1", Trench1xDepot$1),
        Map.entry("Trench1xDepotClimb", Trench1xDepotClimb),
        Map.entry("Trench1xDepotClimb$0", Trench1xDepotClimb$0),
        Map.entry("Trench1xDepotClimb$1", Trench1xDepotClimb$1),
        Map.entry("Trench1xDepotClimb$2", Trench1xDepotClimb$2),
        Map.entry("Trench1xDepotClimb$3", Trench1xDepotClimb$3),
        Map.entry("Trench2xOutpost", Trench2xOutpost),
        Map.entry("Trench2xOutpost$0", Trench2xOutpost$0),
        Map.entry("Trench2xOutpost$1", Trench2xOutpost$1),
        Map.entry("Trench2xOutpost$2", Trench2xOutpost$2),
        Map.entry("Trench2xOutpost$3", Trench2xOutpost$3),
        Map.entry("Trench2xOutpost$4", Trench2xOutpost$4)
    );

    /**
     * Looks up the ChoreoTraj segment of the given overall ChoreoTraj.
     * WARNING: will raise an exception if not called with a valid segment index.
     */
    public ChoreoTraj segment(int segment) {
        var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
        if (traj == null) {
            throw new NullPointerException("Trajectory " + this.name + " does not have segment #" + segment + ".");
        }
        return traj;
    }
    
    // If these methods cause errors because you're not using ChoreoLib,
    // turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
    /**
     * Load an AutoTrajectory directly from a ChoreoTraj, which may be a segment of a larger trajectory.
     */
    public AutoTrajectory asAutoTraj(AutoRoutine routine) {
        if (this.segment.isPresent()) {
            return routine.trajectory(this.name, this.segment.getAsInt());
        }
        return routine.trajectory(this.name);
    }
}
// spotless:on
