// spotless:off
package frc.robot.auto;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import java.util.Map;
import java.util.OptionalInt;

import choreo.auto.AutoRoutine;
import choreo.auto.AutoTrajectory;
// If the 2 imports above cause errors because you're not using ChoreoLib,
// turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.

/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories,
 * and removes the need for JSON parsing to load a trajectory's essential data.
 * DO NOT MODIFY THIS FILE YOURSELF! It is automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    OptionalInt segment,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue
) {
    public static final ChoreoTraj CalibrateMOI = new ChoreoTraj(
        "CalibrateMOI",
        OptionalInt.empty(),
        13.17337,
        new Pose2d(1.8288, 1.8288, Rotation2d.fromRadians(0)),
        new Pose2d(1.8288, 1.8288, Rotation2d.fromRadians(0))
    );
    public static final ChoreoTraj ShootDepot = new ChoreoTraj(
        "ShootDepot",
        OptionalInt.empty(),
        7.61426,
        new Pose2d(3.55938, 4.04324, Rotation2d.fromRadians(3.14159)),
        new Pose2d(1.08795, 4.67495, Rotation2d.fromRadians(1.5708))
    );
    public static final ChoreoTraj Trench2xDepot = new ChoreoTraj(
        "Trench2xDepot",
        OptionalInt.empty(),
        10.26462,
        new Pose2d(3.62538, 7.46701, Rotation2d.fromRadians(0)),
        new Pose2d(2.30439, 7.41287, Rotation2d.fromRadians(0))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj Trench2xDepot$0 = new ChoreoTraj(
        "Trench2xDepot",
        OptionalInt.of(0),
        4.8606,
        new Pose2d(3.62538, 7.46701, Rotation2d.fromRadians(0)),
        new Pose2d(2.29357, 7.38038, Rotation2d.fromRadians(0))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj Trench2xDepot$1 = new ChoreoTraj(
        "Trench2xDepot",
        OptionalInt.of(1),
        5.404020000000001,
        new Pose2d(2.29357, 7.38038, Rotation2d.fromRadians(0)),
        new Pose2d(2.30439, 7.41287, Rotation2d.fromRadians(0))
    );
    public static final ChoreoTraj Trench2xOutpost = new ChoreoTraj(
        "Trench2xOutpost",
        OptionalInt.empty(),
        21.57782,
        new Pose2d(4.25199, 0.62799, Rotation2d.fromRadians(0)),
        new Pose2d(3.04312, 0.52639, Rotation2d.fromRadians(0))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj Trench2xOutpost$0 = new ChoreoTraj(
        "Trench2xOutpost",
        OptionalInt.of(0),
        9.23762,
        new Pose2d(4.25199, 0.62799, Rotation2d.fromRadians(0)),
        new Pose2d(6.59219, 0.57719, Rotation2d.fromRadians(0))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj Trench2xOutpost$1 = new ChoreoTraj(
        "Trench2xOutpost",
        OptionalInt.of(1),
        2.07418,
        new Pose2d(6.59219, 0.57719, Rotation2d.fromRadians(0)),
        new Pose2d(3.0391, 0.52639, Rotation2d.fromRadians(0))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj Trench2xOutpost$2 = new ChoreoTraj(
        "Trench2xOutpost",
        OptionalInt.of(2),
        1.6262299999999996,
        new Pose2d(3.0391, 0.52639, Rotation2d.fromRadians(0)),
        new Pose2d(6.59219, 0.57719, Rotation2d.fromRadians(0))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj Trench2xOutpost$3 = new ChoreoTraj(
        "Trench2xOutpost",
        OptionalInt.of(3),
        6.559330000000001,
        new Pose2d(6.59219, 0.57719, Rotation2d.fromRadians(0)),
        new Pose2d(6.27074, 0.98957, Rotation2d.fromRadians(-1.5708))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj Trench2xOutpost$4 = new ChoreoTraj(
        "Trench2xOutpost",
        OptionalInt.of(4),
        2.0804599999999986,
        new Pose2d(6.27074, 0.98957, Rotation2d.fromRadians(-1.5708)),
        new Pose2d(3.04312, 0.52639, Rotation2d.fromRadians(0))
    );

    /**
     * A map between trajectory names and their corresponding data.
     * This allows for trajectory data to be looked up with strings during runtime.
     */
    public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES = Map.ofEntries(
        Map.entry("CalibrateMOI", CalibrateMOI),
        Map.entry("ShootDepot", ShootDepot),
        Map.entry("Trench2xDepot", Trench2xDepot),
        Map.entry("Trench2xDepot$0", Trench2xDepot$0),
        Map.entry("Trench2xDepot$1", Trench2xDepot$1),
        Map.entry("Trench2xOutpost", Trench2xOutpost),
        Map.entry("Trench2xOutpost$0", Trench2xOutpost$0),
        Map.entry("Trench2xOutpost$1", Trench2xOutpost$1),
        Map.entry("Trench2xOutpost$2", Trench2xOutpost$2),
        Map.entry("Trench2xOutpost$3", Trench2xOutpost$3),
        Map.entry("Trench2xOutpost$4", Trench2xOutpost$4)
    );

    /**
     * Looks up the ChoreoTraj segment of the given overall ChoreoTraj.
     * WARNING: will raise an exception if not called with a valid segment index.
     */
    public ChoreoTraj segment(int segment) {
        var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
        if (traj == null) {
            throw new NullPointerException("Trajectory " + this.name + " does not have segment #" + segment + ".");
        }
        return traj;
    }
    
    // If these methods cause errors because you're not using ChoreoLib,
    // turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
    /**
     * Load an AutoTrajectory directly from a ChoreoTraj, which may be a segment of a larger trajectory.
     */
    public AutoTrajectory asAutoTraj(AutoRoutine routine) {
        if (this.segment.isPresent()) {
            return routine.trajectory(this.name, this.segment.getAsInt());
        }
        return routine.trajectory(this.name);
    }
}
// spotless:on
